import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../../styles/globals.css";
import "../../styles/slim.css";
import "../../styles/slim-input.css";
import "../../styles/slim-btn.css";
import "../../styles/login/login.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Pasbem | Recuperar senha",
  description: "Generated by create next app",
};

export default function ResetPasswordLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="dashboard-wrapper">
      {children}
    </div>
  );
}
