import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../styles/globals.css";
import "../styles/slim.css";
import "../styles/slim-input.css";
import "../styles/slim-btn.css";
import "../styles/slim-select.css";
import "../styles/login/login.css";
import { ToastContainer } from "react-toastify";
import { Loading } from "@/components/Global/Loading";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Pasbem | Login",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="br" className="">
      <head>
        <link href="https://fonts.googleapis.com/css2?family=Kedebideri:wght@400;500;600;700;800;900&family=Yeseva+One&display=swap" rel="stylesheet"></link>
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <ToastContainer />
        <Loading />
        {/* <div>TESTE</div> */}
        {children}
      </body>
    </html>
  );
}
