import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { ToastContainer } from "react-toastify";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Pasbem | Dashboard",
  description: "Generated by create next app",
};

export default function DashboadLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="dashboard-wrapper">
      {children}
    </div>
    // <html lang="br" className="">
    //   <head>
    //     <link href="https://fonts.googleapis.com/css2?family=Kedebideri:wght@400;500;600;700;800;900&family=Yeseva+One&display=swap" rel="stylesheet"></link>
    //   </head>
    //   <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
    //     <ToastContainer />
    //     {children}
    //   </body>
    // </html>
  );
}
